analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - tooling/**
    - flutter/**
    - "**/tooling/**"
    - "**/flutter/packages/**"
    - "**/flutter/bin/cache/**"

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
