import 'plugin_models.dart';

const List<AgentPlugin> bundledPluginCatalog = [
  AgentPlugin(
    id: 'production_agentic_rag_reference',
    name: 'Production Agentic RAG — справочник',
    description: 'Локально синхронизируемые примеры production RAG: chunking, BM25, hybrid retrieval, grading, query rewriting и guardrails.',
    repository: 'jamwithai/production-agentic-rag-course',
    defaultBranch: 'main',
    kind: AgentPluginKind.reference,
    toolName: 'rag_reference_search',
    toolDescription: 'Искать решения и архитектурные примеры в локальной копии курса Production Agentic RAG.',
    commandTemplate: '',
    permissions: [AgentPluginPermission.network],
    bundledSummary: 'Полезные темы: keyword-first retrieval, BM25, section-aware chunking, reciprocal-rank fusion, document grading, query rewriting, out-of-domain guardrails, tracing and caching.',
    enabled: true,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
  AgentPlugin(
    id: 'tempest_harness_reference',
    name: 'T3MP3ST — безопасный справочник harness',
    description: 'Только документация и безопасные шаблоны: воспроизводимые проверки, scope containment, approval gates и отчётность. Наступательные инструменты не запускаются.',
    repository: 'elder-plinius/T3MP3ST',
    defaultBranch: 'main',
    kind: AgentPluginKind.reference,
    toolName: 'security_harness_reference_search',
    toolDescription: 'Искать безопасные архитектурные шаблоны проверки, ограничений и воспроизводимости в локальной документации T3MP3ST.',
    commandTemplate: '',
    permissions: [AgentPluginPermission.network],
    bundledSummary: 'В ядро применимы только безопасные идеи: явная область действия, human approval для рискованных действий, receipts/benchmarks, checkpointing и честное обозначение экспериментальных возможностей.',
    enabled: false,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: true,
  ),
  AgentPlugin(
    id: 'openserp',
    name: 'OpenSERP',
    description: 'Самостоятельно размещаемый поиск Google/Yandex/Baidu/Bing/DuckDuckGo/Ecosia с дедупликацией и извлечением страниц.',
    repository: 'karust/openserp',
    defaultBranch: 'main',
    kind: AgentPluginKind.command,
    toolName: 'openserp_search',
    toolDescription: 'Выполнить сетевой поиск через установленный локальный OpenSERP.',
    commandTemplate: 'openserp search duckduckgo {{input}} --format markdown',
    permissions: [AgentPluginPermission.network, AgentPluginPermission.process],
    bundledSummary: 'Multi-engine SERP, megasearch, URL extraction, JSON/Markdown/Text/NdJSON, filters, cache and resilient mode. Requires network when executing searches.',
    enabled: false,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
  AgentPlugin(
    id: 'free_llm_api_catalog',
    name: 'Каталог бесплатных LLM API',
    description: 'Обновляемый локальный справочник внешних LLM-провайдеров, лимитов и условий использования.',
    repository: 'cheahjs/free-llm-api-resources',
    defaultBranch: 'main',
    kind: AgentPluginKind.reference,
    toolName: 'free_llm_provider_search',
    toolDescription: 'Искать провайдеров и ограничения в синхронизированном каталоге бесплатных LLM API.',
    commandTemplate: '',
    permissions: [AgentPluginPermission.network],
    bundledSummary: 'Catalog of legitimate providers, free quotas, rate limits, trial credits and privacy caveats. Provider data changes often and must be refreshed from GitHub.',
    enabled: false,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
  AgentPlugin(
    id: 'harness_engineering_reference',
    name: 'Awesome Harness Engineering',
    description: 'Справочник по agent loop, planning, context compaction, tool UX, permissions, memory, verification, tracing и human-in-the-loop.',
    repository: 'ai-boost/awesome-harness-engineering',
    defaultBranch: 'main',
    kind: AgentPluginKind.reference,
    toolName: 'harness_engineering_search',
    toolDescription: 'Искать шаблоны надёжного agent harness в локальной копии справочника.',
    commandTemplate: '',
    permissions: [AgentPluginPermission.network],
    bundledSummary: 'Harness primitives: agent loop, decomposition, context delivery/compaction, tools, skills/MCP, permissions, memory, runners, verification, observability, debugging and human oversight.',
    enabled: true,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
  AgentPlugin(
    id: 'self_learning_skills_reference',
    name: 'Self-learning Skills',
    description: 'Справочник по превращению проверенных решений и известных тупиков в повторно используемые навыки.',
    repository: 'Kulaxyz/self-learning-skills',
    defaultBranch: 'main',
    kind: AgentPluginKind.reference,
    toolName: 'self_learning_reference_search',
    toolDescription: 'Искать правила формирования проверенных golden paths в локальной копии Self-learning Skills.',
    commandTemplate: '',
    permissions: [AgentPluginPermission.network],
    bundledSummary: 'Promote a reusable procedure only after a passing check, a named failure pattern and at least one ruled-out dead end. Never persist secret values.',
    enabled: true,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
  AgentPlugin(
    id: 'public_apis_catalog',
    name: 'Public APIs — каталог',
    description: 'Большой обновляемый перечень публичных API по категориям. Любое обращение к выбранному API остаётся отдельным разрешаемым сетевым действием.',
    repository: 'public-apis/public-apis',
    defaultBranch: 'master',
    kind: AgentPluginKind.reference,
    toolName: 'public_api_search',
    toolDescription: 'Искать подходящий API по локальной синхронизированной копии каталога Public APIs.',
    commandTemplate: '',
    permissions: [AgentPluginPermission.network],
    bundledSummary: 'Curated API directory with category, authentication, HTTPS and CORS metadata. Entries are external services and require verification before use.',
    enabled: false,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
  AgentPlugin(
    id: 'openhuman_reference',
    name: 'OpenHuman — интеграционный справочник',
    description: 'Локальная документация по memory tree, checkpointed graphs, workflows, privacy mode, approvals и model routing.',
    repository: 'tinyhumansai/OpenHuman',
    defaultBranch: 'main',
    kind: AgentPluginKind.reference,
    toolName: 'openhuman_reference_search',
    toolDescription: 'Искать архитектурные и интеграционные сведения в локальной документации OpenHuman.',
    commandTemplate: '',
    permissions: [AgentPluginPermission.network],
    bundledSummary: 'Local-first memory trees, compressed context, durable checkpointed graphs, approval-gated workflows, privacy mode, OS-keyring secrets and optional local inference.',
    enabled: false,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
  AgentPlugin(
    id: 'llm_course_reference',
    name: 'LLM Course — справочник',
    description: 'Обновляемые учебные материалы по LLM engineering, evaluation, quantization, fine-tuning, RAG и deployment.',
    repository: 'mlabonne/llm-course',
    defaultBranch: 'main',
    kind: AgentPluginKind.reference,
    toolName: 'llm_course_search',
    toolDescription: 'Искать локальные материалы и примеры в синхронизированной копии LLM Course.',
    commandTemplate: '',
    permissions: [AgentPluginPermission.network],
    bundledSummary: 'Reference material for LLM fundamentals, model engineering, evaluation, quantization, fine-tuning, RAG and deployment. Notebook execution may require optional external dependencies.',
    enabled: false,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
  AgentPlugin(
    id: 'aliens_eye_osint',
    name: 'Aliens Eye OSINT',
    description: 'Отдельный сетевой OSINT-плагин поиска публичных профилей. По умолчанию выключен и требует явного разрешения пользователя.',
    repository: 'arxhr007/Aliens_eye',
    defaultBranch: 'main',
    kind: AgentPluginKind.command,
    toolName: 'username_osint_scan',
    toolDescription: 'Запустить разрешённый пользователем поиск публичного имени пользователя через установленный Aliens Eye.',
    commandTemplate: 'python -m aliens_eye {{input}} --plain --no-nsfw',
    permissions: [AgentPluginPermission.network, AgentPluginPermission.process],
    bundledSummary: 'Asynchronous username checks, heuristic/ML detection, resumable scans, reports and MCP support. Use only for legitimate OSINT and comply with law and site terms.',
    enabled: false,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: true,
  ),
  AgentPlugin(
    id: 'memanto_integration',
    name: 'MEMANTO — внешний адаптер памяти',
    description: 'Опциональная интеграция с локальным MEMANTO. Встроенная память AI Agent работает без этого плагина.',
    repository: 'moorcheh-ai/memanto',
    defaultBranch: 'main',
    kind: AgentPluginKind.integration,
    toolName: 'memanto_recall',
    toolDescription: 'Найти сведения во внешней локальной памяти MEMANTO через безопасную операцию recall.',
    commandTemplate: 'memanto recall {{input}}',
    permissions: [AgentPluginPermission.process, AgentPluginPermission.projectFiles],
    bundledSummary: 'Typed memory, provenance, temporal queries, conflict detection and remember/recall/answer operations. Optional backend may use Docker; built-in AI Agent memory does not require it.',
    enabled: false,
    sourceInstalled: false,
    installedCommit: '',
    latestCommit: '',
    lastCheckedAt: null,
    lastError: '',
    sensitive: false,
  ),
];
